---
title: "Intro to R/RStudio"
output: html_notebook
---

# Console

- Type some maths in

- Say where it is, draw attention to printing of results

- These results aren't "recoverable" - leads on to...

# Global Env

- Assign something to it

- Note: no printing to console, but appears in env.

- Do something to variable

# Data Structures

- Show c() and a data frame (e.g., mtcars/iris/w/e)

- Vector
  - 1D
  - make sequence (e.g., 1-5)
  - use function (mean/sum/etc.)
  - use something vectorised (e.g. sqrt)

- Dataframe
  - 2D (rows, columns)
  - square brakets for indexing...
  - dollar to index named column
  - do a function on a column (each column is a vector)
  
# Script Editor

- Write something in script, save, close, reopen

- Talk about philosophy of scripting (compare to Excel)
  - Reproducibility
    - Some journals ask for code!
  - leaving raw data alone
  - structuring projects

# Packages

- Functionality extends further than "base"

- Install a package, show the list in packages pane

- Use something from package
  - Start with colons
  - then library()
  - (use count from dplyr or something else)#
  
# Other stuff

- Help 

- Plots

- Files

